name: full-pipeline

exp: 
  decider_mode: text-intrscn
  directions: ['left','right','straight','straight-right','straight-left','locational']
  source: selected-frames
  symbols: prompts/symbols.txt
  prompt_file: prompts/prompt.txt
  prompt_img_len: 1
  bbox_match_iou: 0.5
  model_name: gemini
  model_version: gemini-2.0-flash
  openai_api_key_path: keys/openai_api_key.yaml
  gemini_api_key_path: keys/gemini_api_key.yaml
  gemini_detection_api_key: keys/gemini_detection_api_key.yaml
  rot_crops: True
  voting_iter_count: 5
  prompt_img_quality: high
  retry_count: 1
  dataset_dir: gt/fullpipeline_dataset
  result_dir: fullpipeline_results
  crop_gen_model: g-dino
  crop_prompt: Detect ALL 2d bounding boxes for all navigational sign boards present in this image. Also give confidence for each bounding box
  crop_bbox_instr: Return bounding boxes as a JSON array with keys as box_2d and confidence. Never return masks or code fencing. Limit to 25 objects. Add a confidence score for each of your detection.
  crop_temp: 0.5
  gem_output_rotated_crop_folder: fullpipeline_results/frames/gemini_crops/
  fpmatchResponse: fullpipeline_results/g-dino-gemini/unprocessedGTResponse.json
  recg_groundtruth: gt/gt_annotation.json
  excludePath: gt/full-pipeline-exclude-imgs.txt
  
sam:
  model_name: mobile-sam
  box_thresh: 0.1
  text_thresh: 0.1
  nms_thresh: 0.45
  device: cuda
  caption: navigational sign boards
  save_box: True
  save_binary_masks: True
  save_crops: False
  output_ann_box_folder: fullpipeline_results/frames/selected_annotated
  output_binary_mask_folder: fullpipeline_results/frames/selected_binary
  output_crop_folder: fullpipeline_results/frames/selected_crops
  output_rotated_crop_folder: fullpipeline_results/frames/selected_crops_rotated
  nms_process: True
  save_max_conf_box: False
  remove_inner_box: False
  remove_inner_box_margin: 20
  
checkpoints:
  grounding_dino_config_path: /home/ayush/sign-gpt/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  grounding_dino_checkpoint_path: /home/ayush/models/groundingdino_swint_ogc.pth
  mobile_sam_checkpoint: /home/ayush/models/mobile_sam.pt
